package client;

import javax.swing.JOptionPane;

public class ChatWindow extends javax.swing.JFrame {

    /**
     * Creates new form ChatWindow
     */
    public ChatWindow() {
        initComponents();
    }

    private ClientApp clientApp;

    public void setUsername(String username) {
        jLabelName.setText(username);
    }

    public void setClientApp(ClientApp clientApp) {
        this.clientApp = clientApp;
    }

    public String getTopic() {
        return jTextFieldTopicName.getText();
    }

    public String getMessage() {
        return jTextFieldMessage.getText();
    }

    public void clearMessage() {
        jTextFieldMessage.setText("");
    }

    public void appendMessage(String message) {
        jTextAreaChat.append(message + "\n");
    }

    public void setDisconnected() {
        jButtonCreate.setEnabled(false);
        jButtonDelete.setEnabled(false);
        jButtonJoin.setEnabled(false);
        jButtonLeave.setEnabled(false);

        jButtonSend.setEnabled(false);
        jTextFieldMessage.setEnabled(false);
        jTextFieldTopicName.setEnabled(false);
    }

    public javax.swing.JButton getSendButton() {
        return jButtonSend;
    }

    public javax.swing.JTextField getMessageField() {
        return jTextFieldMessage;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelUserControls = new javax.swing.JPanel();
        jLabelName = new javax.swing.JLabel();
        jButtonQuit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaChat = new javax.swing.JTextArea();
        jPanelTopicControls = new javax.swing.JPanel();
        jLabelTopic = new javax.swing.JLabel();
        jTextFieldTopicName = new javax.swing.JTextField();
        jButtonCreate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonJoin = new javax.swing.JButton();
        jButtonLeave = new javax.swing.JButton();
        jPanelChatControls = new javax.swing.JPanel();
        jLabelMessage = new javax.swing.JLabel();
        jButtonSend = new javax.swing.JButton();
        jTextFieldMessage = new javax.swing.JTextField();

        setTitle("Aegis Chat");
        setMinimumSize(new java.awt.Dimension(400, 400));
        setPreferredSize(new java.awt.Dimension(400, 400));

        jLabelName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelName.setText("Name_user");

        jButtonQuit.setText("Quit");
        jButtonQuit.addActionListener(this::jButtonQuitActionPerformed);

        javax.swing.GroupLayout jPanelUserControlsLayout = new javax.swing.GroupLayout(jPanelUserControls);
        jPanelUserControls.setLayout(jPanelUserControlsLayout);
        jPanelUserControlsLayout.setHorizontalGroup(
            jPanelUserControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUserControlsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonQuit)
                .addContainerGap())
        );
        jPanelUserControlsLayout.setVerticalGroup(
            jPanelUserControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUserControlsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUserControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jButtonQuit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextAreaChat.setEditable(false);
        jTextAreaChat.setColumns(20);
        jTextAreaChat.setRows(5);
        jScrollPane1.setViewportView(jTextAreaChat);

        jLabelTopic.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTopic.setText("Topic Name:");

        jButtonCreate.setText("Create");
        jButtonCreate.addActionListener(this::jButtonCreateActionPerformed);

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(this::jButtonDeleteActionPerformed);

        jButtonJoin.setText("Join");
        jButtonJoin.addActionListener(this::jButtonJoinActionPerformed);

        jButtonLeave.setText("Leave");
        jButtonLeave.addActionListener(this::jButtonLeaveActionPerformed);

        javax.swing.GroupLayout jPanelTopicControlsLayout = new javax.swing.GroupLayout(jPanelTopicControls);
        jPanelTopicControls.setLayout(jPanelTopicControlsLayout);
        jPanelTopicControlsLayout.setHorizontalGroup(
            jPanelTopicControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopicControlsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTopicControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTopicControlsLayout.createSequentialGroup()
                        .addComponent(jLabelTopic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTopicName))
                    .addGroup(jPanelTopicControlsLayout.createSequentialGroup()
                        .addGap(0, 4, Short.MAX_VALUE)
                        .addComponent(jButtonCreate)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDelete)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonJoin)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLeave)))
                .addContainerGap())
        );
        jPanelTopicControlsLayout.setVerticalGroup(
            jPanelTopicControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopicControlsLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanelTopicControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTopic)
                    .addComponent(jTextFieldTopicName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelTopicControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCreate)
                    .addComponent(jButtonDelete)
                    .addComponent(jButtonJoin)
                    .addComponent(jButtonLeave))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabelMessage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelMessage.setText("Message:");

        jButtonSend.setText("Send");
        jButtonSend.addActionListener(this::jButtonSendActionPerformed);

        jTextFieldMessage.setToolTipText("Ex: hello!");

        javax.swing.GroupLayout jPanelChatControlsLayout = new javax.swing.GroupLayout(jPanelChatControls);
        jPanelChatControls.setLayout(jPanelChatControlsLayout);
        jPanelChatControlsLayout.setHorizontalGroup(
            jPanelChatControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChatControlsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSend)
                .addContainerGap())
        );
        jPanelChatControlsLayout.setVerticalGroup(
            jPanelChatControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChatControlsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelChatControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMessage)
                    .addComponent(jButtonSend)
                    .addComponent(jTextFieldMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelUserControls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelChatControls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTopicControls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelUserControls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTopicControls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelChatControls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitActionPerformed
        if (clientApp != null) {
            clientApp.disconnect();
        }

        new ClientWindow().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonQuitActionPerformed

    private void jButtonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateActionPerformed
        String topic = getTopic();

        if (topic.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Informe o nome do tópico.",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        clientApp.createTopic(topic);
    }//GEN-LAST:event_jButtonCreateActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        String topic = getTopic();

        if (topic.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Informe o nome do tópico para deletar.",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        clientApp.deleteTopic(topic);
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJoinActionPerformed
        String topic = getTopic();

        if (topic.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Informe o nome do tópico para entrar.",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        clientApp.subscribeTopic(topic);
    }//GEN-LAST:event_jButtonJoinActionPerformed

    private void jButtonLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeaveActionPerformed
        String topic = getTopic();

        if (topic.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Informe o nome do tópico para sair.",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        clientApp.unsubscribeTopic(topic);
    }//GEN-LAST:event_jButtonLeaveActionPerformed

    private void jButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendActionPerformed
        String message = getMessage();
        String topic = getTopic();

        if (topic.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Informe um tópico antes de enviar mensagem.",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (message.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Digite uma mensagem.",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        clientApp.publishTopic(topic, message);
        clearMessage();
    }//GEN-LAST:event_jButtonSendActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonJoin;
    private javax.swing.JButton jButtonLeave;
    private javax.swing.JButton jButtonQuit;
    private javax.swing.JButton jButtonSend;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelTopic;
    private javax.swing.JPanel jPanelChatControls;
    private javax.swing.JPanel jPanelTopicControls;
    private javax.swing.JPanel jPanelUserControls;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaChat;
    private javax.swing.JTextField jTextFieldMessage;
    private javax.swing.JTextField jTextFieldTopicName;
    // End of variables declaration//GEN-END:variables
}
