package client;

public class ClientWindow extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClientWindow.class.getName());

    private ClientApp clientApp;

    /**
     * Creates new form ClientWindow
     */
    public ClientWindow() {
        initComponents();
        configLabels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBackground = new javax.swing.JPanel();
        jPanelControls = new javax.swing.JPanel();
        jLabelHost = new javax.swing.JLabel();
        jTextFieldHost = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldPort = new javax.swing.JTextField();
        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jButtonEnter = new javax.swing.JButton();
        jLabelExcName = new javax.swing.JLabel();
        jLabelExcHost = new javax.swing.JLabel();
        jLabelExcPort = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aegis Client");
        setMinimumSize(new java.awt.Dimension(450, 375));
        setPreferredSize(new java.awt.Dimension(450, 375));

        jPanelBackground.setLayout(new java.awt.GridBagLayout());

        jLabelHost.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelHost.setText("Host:");

        jTextFieldHost.setText("localhost");
        jTextFieldHost.setToolTipText("Ex: localhost");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Port:");

        jTextFieldPort.setText("5000");
        jTextFieldPort.setToolTipText("Ex: 5000");

        jLabelName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelName.setText("Name:");

        jTextFieldName.setToolTipText("Ex: User");

        jButtonEnter.setText("Enter");
        jButtonEnter.addActionListener(this::jButtonEnterActionPerformed);

        jLabelExcName.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelExcName.setForeground(new java.awt.Color(255, 0, 0));
        jLabelExcName.setText("*Name empty");

        jLabelExcHost.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelExcHost.setForeground(new java.awt.Color(255, 0, 0));
        jLabelExcHost.setText("*Host empty");

        jLabelExcPort.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelExcPort.setForeground(new java.awt.Color(255, 0, 0));
        jLabelExcPort.setText("*Port empty");

        javax.swing.GroupLayout jPanelControlsLayout = new javax.swing.GroupLayout(jPanelControls);
        jPanelControls.setLayout(jPanelControlsLayout);
        jPanelControlsLayout.setHorizontalGroup(
            jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControlsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelControlsLayout.createSequentialGroup()
                        .addComponent(jLabelName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelControlsLayout.createSequentialGroup()
                                .addComponent(jLabelExcName)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFieldName)))
                    .addGroup(jPanelControlsLayout.createSequentialGroup()
                        .addComponent(jLabelHost)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelControlsLayout.createSequentialGroup()
                                .addComponent(jTextFieldHost, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addComponent(jLabelExcHost))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelExcPort)
                            .addComponent(jTextFieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelControlsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonEnter)))
                .addContainerGap())
        );
        jPanelControlsLayout.setVerticalGroup(
            jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControlsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHost)
                    .addComponent(jTextFieldHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelExcHost)
                    .addComponent(jLabelExcPort))
                .addGap(17, 17, 17)
                .addGroup(jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelExcName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEnter)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelBackground.add(jPanelControls, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnterActionPerformed
        try {
            boolean hasError = false;

            if (jTextFieldHost.getText().isEmpty()) {
                jLabelExcHost.setVisible(true);
                hasError = true;
            }

            if (jTextFieldPort.getText().isEmpty()) {
                jLabelExcPort.setVisible(true);
                hasError = true;
            }

            if (jTextFieldName.getText().isEmpty()) {
                jLabelExcName.setVisible(true);
                hasError = true;
            }

            if (hasError) {
                return;
            }

            String host = jTextFieldHost.getText();
            int port = Integer.parseInt(jTextFieldPort.getText());
            String name = jTextFieldName.getText();

            ChatWindow chatWin = new ChatWindow();
            clientApp = new ClientApp(host, port, name, chatWin);

            boolean connected = clientApp.connect();

            if (!connected) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Nome já está em uso ou erro ao conectar.",
                        "Erro",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            chatWin.setClientApp(clientApp);
            chatWin.setUsername(name);
            chatWin.setVisible(true);

            this.setVisible(false);

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Não foi possível conectar ao servidor.",
                    "Erro",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonEnterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Default".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ClientWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelExcHost;
    private javax.swing.JLabel jLabelExcName;
    private javax.swing.JLabel jLabelExcPort;
    private javax.swing.JLabel jLabelHost;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JPanel jPanelControls;
    private javax.swing.JTextField jTextFieldHost;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPort;
    // End of variables declaration//GEN-END:variables

    private void configLabels() {
        this.jLabelExcHost.setVisible(false);
        this.jLabelExcPort.setVisible(false);
        this.jLabelExcName.setVisible(false);
    }
}
