# Configuração de Certificados
# Caminho para o certificado do cliente (usado apenas pelos clientes)
client.cert.path=client-cert.crt

# Caminho para o certificado da CA do servidor (usado por cliente e servidor)
server.cert.path=server-ca.crt
