# Configuração de Certificados
# Caminho para o certificado do cliente (usado apenas pelos clientes)
client.cert.path=certs/client-cert.crt

# Caminho para o certificado da CA do servidor (usado por cliente e servidor)
server.cert.path=certs/server-ca.crt
